language: python

addons:
  apt:
    config:
      retries: true

cache:
  apt: true
  pip: true

matrix:
  include:
    - os: linux
      dist: xenial
      python: 2.7
      env: TOXENV=py27
      name: "2.7 Xenial"
    - os: linux
      dist: xenial
      python: 3.6
      env: TOXENV=py36
      name: "3.6 Xenial"
    - os: linux
      dist: xenial
      python: 3.7
      env: TOXENV=py37
      name: "3.7 Xenial"
    - os: linux
      dist: xenial
      python: 3.8
      env: TOXENV=py38
      name: "3.8 Xenial"
    - os: linux
      dist: bionic
      python: 3.9
      env: TOXENV=py39-pre-commit
      name: "3.9 Bionic"

before_install:
  - sudo apt-get install -y tesseract-ocr
  - sudo apt-get install -y tesseract-ocr-fra
  - tesseract --version
  - tesseract --list-langs

install:
  pip install tox

script:
  tox

notifications:
  email: false
